url: https://byrocketscience.github.io
baseurl: 

# Site settings
name: Rocket Science Web Studio
company: "Rocket Science, LLC"
title: "Android and iOS App Developement | Web Development in Norfolk, VA"
address: "259 Granby St. #250, Norfolk, VA 23510"
email: contact@byrocketscience.com
description: "Rocket Science Web Studio is a web design and app development agency located in Norfolk, VA that helps everyday people turn their ideas into finished and marketable products. We serve Norfolk, Virginia Beach, Chesapeake, and the rest of the United States."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 26A69A
  secondary: 00695C
  secondary-dark: 333

# Team names, titles and social links
people:
- name: David Jenkins
  pic: david
  position: Project Lead Developer
  colslg: 3
  social:
    - title: twitter
      url: https://twitter.com/boarderdav
    - title: facebook
      url: https://www.facebook.com/boarderdav
    - title: linkedin
      url: https://www.linkedin.com/in/davidjenkinspe

- name: Jose Mateo
  pic: jose
  position: Android and Web Developer
  colslg: 3
  social:
    - title: globe
      url: http://mateoj.com
    - title: google-plus
      url: https://plus.google.com/+JoseMateoA/
    - title: linkedin
      url: http://www.linkedin.com/in/josemateoa

- name: Jake Spracher
  pic: jake
  position: iOS and Web Developer
  colslg: 3
  social:
    - title: globe
      url: http://jakespracher.com
    - title: twitter
      url: https://twitter.com/jakespracher
    - title: linkedin
      url: http://www.linkedin.com/in/jakespracher

- name: Franck Tchouambou
  pic: franck
  position: Growth Hacker & Business Developer
  colslg: 3
  social:
    - title: twitter
      url: https://www.twitter.com/thyfranck
    - title: facebook
      url: https://www.fb.com/Tchouambou
    - title: linkedin
      url: https://www.linkedin.com/in/franckt

- name: Chandler Perry
  pic: chandler
  position: Videographer
  colslg: 3
  social:
    - title: youtube-square
      url: "https://www.youtube.com/user/premadepros"
    - title: vimeo
      url: "https://vimeo.com/user9177602"

- name: Edanry Rivera
  pic: edanry
  position: Social Media Director
  colslg: 3
  social:
    - title: facebook
      url: "https://www.facebook.com/edanry.rivera"

- name: Anton Lisovsky
  pic: anton
  position: Web Developer
  colslg: 3
  social:
    - title: twitter
      url: "https://twitter.com/xzarxzez"
    - title: github
      url: "https://github.com/antlis"

- name: Rinat Yahin
  pic: rinat
  position: iOS Developer
  colslg: 3
  social:
    - title: twitter
      url: "https://twitter.com/_6234530394982"
    - title: linkedin
      url: "https://ru.linkedin.com/pub/rinat-yahin/b2/65b/ab4"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/byrocketscience
  - title: facebook
    url: https://www.facebook.com/ByRocketScience
  - title: google-plus
    url: https://plus.google.com/105510692232230355051
  - title: instagram
    url: http://instagram.com/ByRocketScience

# Postal address (add as many lines as necessary)
#address:
#  - line: 308 Westover Avenue
#  - line: Norfolk, VA 23507

# Build settings
markdown: kramdown
permalink: pretty
